name: dart_nostr
description: Develop Scalable Dart/Flutter Nostr clients quickly and easily
version: 7.0.1
repository: https://github.com/anasfik/nostr/

environment:
  sdk: ">=3.0.0 <=3.2.5"

dependencies:
  bip340: ^0.1.0
  equatable: ^2.0.5
  convert: ^3.1.1
  crypto: ^3.0.2
  http: ^0.13.5
  meta: ^1.8.0
  bech32: ^0.2.2
  hex: ^0.2.0
  bip32_bip44: ^1.0.0
  bip39: ^1.0.6

dev_dependencies:
  dart_code_metrics: ^5.7.2
  lints:
  test:
  very_good_analysis: ^5.1.0
